server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://db.mjgf.io:3306/wface_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: ayalost321
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
      host: redis.mjgf.io
      port: 6379
      database: 4
      lettuce:
        pool:
          min-idle: 10
          max-wait: 5000ms
          max-idle: 50
          max-active: 100


mybatis-plus:
  #typeEnumsPackage: com.mjgf.biz.payment.enums;com.wface.citic.enums
  typeAliasesPackage: com.example.*.entity
  mapper-locations: classpath*:/mappers/*Mapper.xml
  global-config:
    refresh-mapper: false
    id-type: 0
    db-column-underline: true
  configuration:
    multipleResultSetsEnabled: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazyLoadingEnabled: true
    cache-enabled: true


logging:
  level:
    org.springframework:
      security: debug







