server:
  port: 8088

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: localhost:8087/.well-known/jwks.json

logging:
  level:
    org.springframework:
      security: debug


