server:
  port: 8086

spring:
  profiles:
    active: test

  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://beautybase-dm.mysql.rds.aliyuncs.com:3306/wface_finance?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: dev
    password: Meijigongfang2018
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
      host: redis.mjgf.io
      port: 6379
      database: 4
      lettuce:
        pool:
          min-idle: 10
          max-wait: 5000ms
          max-idle: 50
          max-active: 100

cache:
  defaultExpiration: 86400
  expireMap:
    user: 300
    smsCode: 90

logging:
  level:
    org.springframework:
      security: debug
      data: debug

wechat:
  miniapp:
    appid: wx3a64f83d3b7e9fff
    secret: 0f4bc192bed75951ddf8e9aebb93e13f





